### ISSUE TITLE
Runner crash on first request on Linux (and maybe others)

### ISSUE THREAD

**Issue by WinPlay02** [Safe-DS/Runner#42]
### Describe the bug

The runner crashes on first request (usually program message)

### To Reproduce

1. Open VSCode with Safe-DS extension
2. Click on Run button for any Safe-DS source file

### Expected behavior

The runner executes the program

### Additional Context (optional)

I would propose to replace the (legacy) flask stack with a quart (successor in a way of flask) stack that does not require monkey patching python internals. This has the added benefit to allow async python functions and in turn being possibly more efficient.

Furthermore, a migration to the socket.io protocol is still possible although not as easy as changing the dependency in flask.

**Comment by lars-reimann** [comment]
Is this related to the issue reported by @SmiteDeluxe?

**Comment by lars-reimann** [comment]
Websockets seem to be [supported out-of-the-box](https://pgjones.gitlab.io/quart/discussion/websockets_discussion.html) by `quart`. How could `socket.io` be integrated (just see to ensure we don't lose options by migrating? I guess [`python-socketio`](https://github.com/miguelgrinberg/python-socketio/tree/main/examples/server/asgi) could be used for this purpose?

**Comment by lars-reimann** [comment]
[`litestar`](https://github.com/litestar-org/litestar) might also be a lightweight ASGI framework to consider.

**Comment by WinPlay02** [comment]
> Is this related to the issue reported by @SmiteDeluxe?

This is the same issue

> Websockets seem to be [supported out-of-the-box](https://pgjones.gitlab.io/quart/discussion/websockets_discussion.html) by `quart`. How could `socket.io` be integrated (just see to ensure we don't lose options by migrating? I guess [`python-socketio`](https://github.com/miguelgrinberg/python-socketio/tree/main/examples/server/asgi) could be used for this purpose?

The `python-socketio` library is the way to go, exactly. `python-socketio` received support for ASGI a long time ago.

> [`litestar`](https://github.com/litestar-org/litestar) might also be a lightweight ASGI framework to consider.

I chose `quart` as it is the successor to `flask` and it seemed the most lightweight. I additionally also considered `fastapi`.

**Comment by WinPlay02** [comment]
Also see the `fix-linux-startup-error` branch, for a preview.

> Furthermore, a migration to the socket.io protocol is still possible although not as easy as changing the dependency in flask.

The potential future usage of was `socket.io` was considered in the choice of `quart`.
