### ISSUE TITLE
CUDA tensors not released in time

### ISSUE THREAD

**Issue by SmiteDeluxe** [Safe-DS/Runner#78]
### Describe the bug

Whenever you fetch an image through a call such as getHistogram(), the CUDA shared tensors are not all released. Then when you execute an image call on the same column again, the execution crashes because of "RuntimeError: Attempted to send CUDA tensor received from another process; this is not currently supported. Consider cloning before sending."
2 Image calls on different columns work fine. Also 1 of them in first execution, the other in second execution.

### To Reproduce

1. Import a table
2. from any column get the histogram
3. execute pipeline
4. execute again for the crashed execution

### Expected behavior

Release of tensors probably and thus no crashes.

### Screenshots (optional)

![image](https://github.com/Safe-DS/DSL/assets/97200640/337c6010-1939-4851-a354-82134e35e3c0)
and then second execution:
![WhatsApp Bild 2024-04-05 um 15 10 51_5c372a57](https://github.com/Safe-DS/DSL/assets/97200640/f5ff7223-91c7-4c62-90f1-8f88bde400c4)

**Comment by lars-reimann** [comment]
@SmiteDeluxe Is this still happening?

**Comment by WinPlay02** [comment]
> @SmiteDeluxe Is this still happening? I could not reproduce this with current versions of the runner, and I've not seen it during the evaluation either.

This could have been fixed by #87, as IPC with placeholders was changed to serialize values first, then send the shared-memory location to the manager process instead of directly sending the values to the manager process.
(Maybe this previously also caused the diagrams to be sometimes empty?)

**Comment by SmiteDeluxe** [comment]
> @SmiteDeluxe Is this still happening? I could not reproduce this with current versions of the runner, and I've not seen it during the evaluation either.

Don't think so. Have tried to replicate by showing the same image twice but all seems to be working.
