### ISSUE TITLE
Improve startup time of workers

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Runner#85]
During evaluation, we observed delays ranging from 3s to 20s+ between a program message and the first values coming back, regardless of the size of the data. For better usability, this time should be reduced as much as possible, since this 

* delays the table view showing up 
* and later causes another delay for the profiling.

**Comment by lars-reimann** [comment]
A few modules in the library constitute most of the delay:

* `(Measure-Command { python -c "import seaborn" }).TotalSeconds`: 1.21s
* `(Measure-Command { python -c "import torch" }).TotalSeconds`: 1.24s
* `(Measure-Command { python -c "import torchvision" }).TotalSeconds`: 1.90s
* `(Measure-Command { python -c "import openpyxl" }).TotalSeconds`: 0.26s

We should get major improvements regarding startup by:

1. Lazily loading our own classes in `__init__` files ([`apipkg`](https://github.com/pytest-dev/apipkg)) _why is this not the default behavior in Python?!_
2. Lazily importing external libraries.

Unfortunately, many libraries currently import all their stuff into a global package, so if we use anything from, say `seaborn`, there will still be the 1.21s. This can only be fixed by the libraries themselves.

Regarding the runner, we will need to have a primed process ready that can handle the execution of the next pipeline. Ideally, we would also keep those processes alive and reset them after pipeline execution is done, so we don't have the startup delay again and again.

**Comment by WinPlay02** [comment]
> Ideally, we would also keep those processes alive and reset them after pipeline execution is done, so we don't have the startup delay again and again.

@lars-reimann This is somewhat supported, as `metapath` (for loading our pipelines) is already reset after a pipeline ends. The process could theoretically be reused, but this behavior would not guarantee correctness in all cases. States from external libraries (like `seaborn`) however, is not reset.

> Regarding the runner, we will need to have a primed process ready that can handle the execution of the next pipeline.

I'll try something out for tomorrow, maybe something like that can be achieved.

**Comment by lars-reimann** [comment]
There's also a new release of the library now, containing your hash functions and your other improvements, as well as the lazy imports.
